= A Painted On Smile =


 


 


As I put on my hat and check my reflection


Inside I feel empty and fragile,


Remembering the past﻿ and our history,


Arranging my painted-on smile.


 
 
 
 
 


In the car the radio chatters away


But I've not been listening for quite a while.


I'm stuck in the past, reliving good times


As I practice my painted-on smile.


 
 
 
 
 


At the church there is a profusion of flowers,


Old friends with whom to reconcile.


I feel lost and detached, a soul wandering alone


Behind my painted-on smile.






 


The service is lovely, hardly a dry eye,


Rapt faces turned heavenwards for a while,


Hymns sung, wishes for happiness beamed.


Yet I struggle to follow with my painted-on smile.






 


As the organ begins to swell


And you walk down the aisle


Escorting your beautiful new bride


Cracks appear in my painted-on smile.






 


The speeches are made, champagne glasses clinked,


Congratulations shouted by all.


But standing apart with a chill in my heart


Is me with my painted-on smile.  
